# General options
output_dir: ~

# Model definiton
model_module: ~
model_function: f
dimensions: 4
lower_bounds: [50, 52, 0.04, 0.01]
upper_bounds: [60, 62, 0.05, 0.02]

# RSQTOA hyper-parameter
epsilon: 1e-1
sampling_strategy: "latin"
regression_samples: 4
test_samples: 2
test_values: 5
max_taylor_order: 2
debug: True

# Sampling 
periodic_regression_samples: 0
exponential_regression_samples: 0
regression_selection: "greedy"

# Domain decomposition
subspace_ordering: "default"
subspace_depth: 0
subspace_threshold: 1e-3
subspace_needs_regression: True
subspace_selection: "best"
subspace_expansion_steps: 3
subspace_reduction_steps: 3
