# General options
output_dir: ~

# Model definiton
model_module: ~
model_function: diffusion
dimensions: 3
lower_bounds: [0, 0, 0]
upper_bounds: [10, 1, 1]

# RSQTOA hyper-parameter
epsilon: 1e-1
sampling_strategy: "latin"
regression_samples: 30
test_samples: 2
test_values: 4
max_taylor_order: 3
debug: True

# Sampling
periodic_regression_samples: 0
exponential_regression_samples: 0
regression_selection: "greedy"

# Domain decomposition
subspace_ordering: "max_error"
subspace_depth: 2
subspace_threshold: 1e-3
subspace_needs_regression: True
subspace_selection: "greedy"
subspace_expansion_steps: 3
subspace_reduction_steps: 3
